import {IDX_BLEIBEN} from "./utils/verbs-mapping"
import {IDX_ESSEN} from "./utils/verbs-mapping"
import {IDX_SCHEIDEN} from "./utils/verbs-mapping"
import {IDX_FALLEN} from "./utils/verbs-mapping"
import {IDX_FINDEN} from "./utils/verbs-mapping"
import {IDX_GEBEN} from "./utils/verbs-mapping"
import {IDX_GEHEN} from "./utils/verbs-mapping"
import {IDX_GEWINNEN} from "./utils/verbs-mapping"
import {IDX_HALTEN} from "./utils/verbs-mapping"
import {IDX_HEISSEN} from "./utils/verbs-mapping"
import {IDX_HELFEN} from "./utils/verbs-mapping"
import {IDX_KOMMEN} from "./utils/verbs-mapping"
import {IDX_LASSEN} from "./utils/verbs-mapping"
import {IDX_LAUFEN} from "./utils/verbs-mapping"
import {IDX_NEHMEN} from "./utils/verbs-mapping"
import {IDX_SEHEN} from "./utils/verbs-mapping"
import {IDX_SITZEN} from "./utils/verbs-mapping"
import {IDX_SPRECHEN} from "./utils/verbs-mapping"
import {IDX_STEHEN} from "./utils/verbs-mapping"
import {IDX_TRAGEN} from "./utils/verbs-mapping"
import {IDX_VERLIEREN} from "./utils/verbs-mapping"
import {IDX_ZIEHEN} from "./utils/verbs-mapping"
import {IDX_TUN} from "./utils/verbs-mapping"

// CHANGE HERE SECOND VARIABLE TO CHANGE THE VERB BEING PLAYED
export const INIT_IDX = IDX_SCHEIDEN;
