name: build and deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 14.x
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      REMOTE_HOST: 49.12.37.122
      SOURCE: "build/"
      TARGET: /var/opt/unregelapp/app

    steps:
      - uses: actions/checkout@v2
      - name: Download build files
        uses: actions/download-artifact@v1
        with:
          name: build
      - run: echo "Deploy to ${REMOTE_HOST}"
      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SLISSNER_CI_PRIVATE_KEY }}
      - run: ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
      - run: rsync -rae ssh --progress ${SOURCE} root@${REMOTE_HOST}:${TARGET}
